- hosts: localhost
  vars:
    source_key: "./.ssh/github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - ubuntu-install
  - name: Update Pacman
    shell: sudo sudo pacman -Syu --noconfirm
    tags:
      - arch-install
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/nvim.yml
    - include: tasks/repos.yml
    - include: tasks/tmux.yml
    - include: tasks/dotfiles.yml
    - include: tasks/finalize.yml
