- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:PTMargarido/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/github"
    version: main
  tags:
    - arch-install
    - ubuntu-install
- name: Stowing files
  shell: cd $HOME/.dotfiles/ && ./stow
  tags:
    - arch-install
    - ubuntu-install
