- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "ptmmmargarido@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Pedro Margarido"
  tags:
  - git-personal
