- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - ubuntu-install
    
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - ubuntu-install
    
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - ubuntu-install
    
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - ubuntu-install
    
- name: Installing neovim
  shell: "sudo sudo pacman -Sy neovim --noconfirm"
  tags:
    - arch-install
