- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:GorillazTech/xtradebot-deploy.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/xtradebot-deploy"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/github"
    version: main
  tags:
    - arch-install
    - ubuntu-install
